CREATE TABLE VEHICLE_DETAILS (
  Id INT PRIMARY KEY,
  VIN_NUMBER VARCHAR(30) NOT NULL,
  MANUFACTURER VARCHAR (20) NOT NULL,
  MODEL VARCHAR (30) NOT NULL,
  PRODUCTION_DATE DATE DEFAULT NULL,
  CAR_PRICE DOUBLE DEFAULT NULL,
  NEW_CAR BOOLEAN DEFAULT NULL,
  ENGINE_POWER INT DEFAULT NULL
);

CREATE TABLE LEASING_APPLICATION_DETAILS (
  Id INT PRIMARY KEY,
  LEASING_PERIOD INT NOT NULL,
  INTEREST_RATE DOUBLE NOT NULL,
  INITIAL_PAYMENT DOUBLE NOT NULL,
  MONTHLY_PAYMENT_AMOUNT DOUBLE NULL,
  STATUS VARCHAR(10) DEFAULT NULL
);

CREATE TABLE PERSON_DETAILS (
  Id INT PRIMARY KEY,
  MONTHLY_INCOME INT NOT NULL
);