CREATE TABLE IF NOT EXISTS PERSON_DETAILS (
  Id INT PRIMARY KEY AUTO_INCREMENT,
  PERSON_CODE VARCHAR(11) NOT NULL,
  FIRST_NAME VARCHAR(10) NOT NULL,
  LAST_NAME VARCHAR(10) NOT NULL,
  WORK_PLACE VARCHAR(20) NOT NULL,
  MONTHLY_INCOME INT NOT NULL
);
CREATE TABLE IF NOT EXISTS VEHICLE_DETAILS (
  Id INT PRIMARY KEY AUTO_INCREMENT,
  VIN_NUMBER VARCHAR(30) NOT NULL,
  MANUFACTURER VARCHAR (20) NOT NULL,
  MODEL VARCHAR (30) NOT NULL,
  PRODUCTION_DATE DATE DEFAULT NULL,
  CAR_PRICE DOUBLE DEFAULT NULL,
  NEW_CAR BOOLEAN DEFAULT NULL,
  ENGINE_POWER INT DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS LEASING_APPLICATION_DETAILS (
  Id INT PRIMARY KEY AUTO_INCREMENT,
  LEASING_PERIOD INT NOT NULL,
  INTEREST_RATE DOUBLE NOT NULL,
  INITIAL_PAYMENT DOUBLE NOT NULL,
  MONTHLY_PAYMENT_AMOUNT DOUBLE NULL,
  STATUS VARCHAR(10) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS LEASING_APPLICATION_RULES (
  Id INT PRIMARY KEY AUTO_INCREMENT,
  RULE_NAME VARCHAR (20) NOT NULL,
  RULE_TYPE VARCHAR(20) NOT NULL,
  VALUE VARCHAR(10) NULL,
  VALID_TO DATE DEFAULT NULL,
  UPDATE_DATE DATE DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS LOGS (
  Id INT PRIMARY KEY AUTO_INCREMENT,
  REQUEST_DATE DATE DEFAULT NULL,
  METHOD VARCHAR(10) DEFAULT NULL,
  URL VARCHAR(20) DEFAULT NULL,
  RESPONSE_STATUS INT DEFAULT NULL

);